skydash/skydash/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('custom_admin/', include('custom_admin.urls')),
    path('ticket/', include('ticket.urls', namespace='ticket'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skydash/ticket/urls.py
from django.urls import path

from ticket import views

app_name = 'ticket'

urlpatterns = [
    path('create/', views.createTicket, name='create'),
    path('update/<str:pk>/', views.updateTicket, name='update'),
    path('delete/<str:pk>/', views.deleteTicket, name='delete'),
]

skydash/users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path('login/', views.loginForMentor, name='login'),
    path('logout/', views.logoutMentor, name='logout'),

    path('register/', views.register, name='register'),
    path('update/<str:pk>', views.update, name='update'),
    path('delete/<str:pk>', views.delete, name='delete')
]

skydash/ticket/models.py
from django.db import models
from django.db.models.signals import pre_save

import uuid

from users.models import Profile
from courses.models import Course


# Create your models here.

class Ticket(models.Model):
    STATUS_CHOICES = (
        ('New', 'New'),
        ('In Process', 'In process'),
        ('Finished', 'Finished')
    )

    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, unique=True)
    mentor = models.ForeignKey(Profile, on_delete=models.CASCADE, limit_choices_to={'prof': 'Mentor'},
                               related_name='related_to_mentor')
    student = models.ForeignKey(Profile, on_delete=models.CASCADE, limit_choices_to={'prof': 'Student'},
                                related_name='related_to_student')
    created = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    course = models.ManyToManyField(Course, blank=True)
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default='New')
    price = models.DecimalField(max_digits=6, decimal_places=2, editable=False, blank=True, null=True)
    salary = models.DecimalField(max_digits=6, decimal_places=2, editable=False, blank=True, null=True)

    def __str__(self):
        return f"{self.student.username}'s ticket | Status - {self.status}"

skydash/ticket/forms.py
from django.forms import ModelForm
from django import forms

from ticket.models import Ticket


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ['mentor', 'student', 'location', 'course']
        widgets = {
            'course': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(TicketForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update(
                {
                    'class': 'form-control form-control-lg',
                    'placeholder': field.label,
                    'style': 'color: black'
                })

        self.fields['course'].widget.attrs.update(
            {
                'class': '',
            }
        )


class updateStatus(ModelForm):
    class Meta:
        model = Ticket
        fields = ['status']

    def __init__(self, *args, **kwargs):
        super(updateStatus, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update(
                {
                    'class': 'form-control form-control-lg',
                    'placeholder': field.label,
                    'style': 'color: black'
                })

skydash/ticket/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from ticket.forms import TicketForm, updateStatus
from ticket.models import Ticket


# Create your views here.

@login_required(login_url='login')
def createTicket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.save()
            form.save_m2m()
            form.save()
            return redirect('tickets')
    else:
        form = TicketForm()

    context = {
        'form': form,
    }

    return render(request=request, template_name='ticket/create.html', context=context)


@login_required(login_url='login')
def updateTicket(request, pk):
    ticket = Ticket.objects.get(id=pk)

    if request.method == 'POST':
        form = updateStatus(request.POST, instance=ticket)
        if form.is_valid():
            form.save()
            return redirect('tickets')
    else:
        form = updateStatus(instance=ticket)

    context = {
        'form': form,
        'pk': pk,
    }

    return render(request=request, template_name='ticket/update.html', context=context)


@login_required(login_url='login')
def deleteTicket(request, pk):
    ticket = Ticket.objects.get(id=pk)
    ticket.delete()

    return redirect('tickets')

skydash/ticket/templates/ticket/create.html
{% extends 'users/main.html' %}

{% load static %}

{% block content %}
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center auth px-0">
                <div class="row w-100 mx-0">
                    <div class="col-lg-4 mx-auto">
                        <div class="auth-form-light text-left py-5 px-4 px-sm-5">
                            <div class="brand-logo">
                                <img src="{% static 'images/logo.svg' %}" alt="logo">
                            </div>
                            <h4>New order</h4>
                            <form class="pt-3" method="POST">
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group">

                                        {{ field }}

                                        {% for error in field.errors %}
                                            <h6 class="font-weight-light"
                                                style="color: darkred; margin-top: 2vh">{{ error }}</h6>
                                        {% endfor %}

                                    </div>
                                {% endfor %}
                                <div class="mt-3">
                                    <input class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn"
                                           type="submit" value="ORDER">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
{% endblock content %}

skydash/ticket/templates/ticket/update.html
{% extends 'users/main.html' %}

{% load static %}

{% block content %}
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center auth px-0">
                <div class="row w-100 mx-0">
                    <div class="col-lg-4 mx-auto">
                        <div class="auth-form-light text-left py-5 px-4 px-sm-5">
                            <div class="brand-logo">
                                <img src="{% static 'images/logo.svg' %}" alt="logo">
                            </div>
                            <h4>Update Status</h4>
                            <form class="pt-3" method="POST">
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group">

                                        <h6 cclass="font-weight-light">{{ field.label }}</h6>
                                        {{ field }}

                                        {% for error in field.errors %}
                                            <h6 class="font-weight-light"
                                                style="color: darkred; margin-top: 2vh">{{ error }}</h6>
                                        {% endfor %}

                                    </div>
                                {% endfor %}

                                <div class="mt-3">
                                    <input class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn"
                                           type="submit" value="UPDATE">
                                </div>
                            </form>
                            <a href="{% url 'ticket:delete' pk %}"
                               class="mt-3 btn btn-block btn-lg font-weight-medium auth-form-btn"
                               style="background-color: red; color: white">DELETE</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
{% endblock content %}