skydash/custom_admin/urls.py
from django.urls import path

from custom_admin import views

urlpatterns = [
    path('users/', views.accounts, name='accounts'),
    path('courses/', views.courses, name='courses'),
    path('tickets/', views.tickets, name='tickets')
]

skydash/skydash/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('custom_admin/', include('custom_admin.urls')),
    path('ticket/', include('ticket.urls', namespace='ticket'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skydash/ticket/urls.py
from django.urls import path

from ticket import views

app_name = 'ticket'

urlpatterns = [
    path('create/', views.createTicket, name='create'),
    path('update/<str:pk>/', views.updateTicket, name='update'),
    path('delete/<str:pk>/', views.deleteTicket, name='delete'),
]

skydash/users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path('login/', views.loginForMentor, name='login'),
    path('logout/', views.logoutMentor, name='logout'),

    path('register/', views.register, name='register'),
    path('update/<str:pk>', views.update, name='update'),
    path('delete/<str:pk>', views.delete, name='delete')
]

skydash/custom_admin/models.py
from django.db import models

# Create your models here.

skydash/ticket/models.py
from django.db import models
from django.db.models.signals import pre_save

import uuid

from users.models import Profile
from courses.models import Course


# Create your models here.

class Ticket(models.Model):
    STATUS_CHOICES = (
        ('New', 'New'),
        ('In Process', 'In process'),
        ('Finished', 'Finished')
    )

    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, unique=True)
    mentor = models.ForeignKey(Profile, on_delete=models.CASCADE, limit_choices_to={'prof': 'Mentor'},
                               related_name='related_to_mentor')
    student = models.ForeignKey(Profile, on_delete=models.CASCADE, limit_choices_to={'prof': 'Student'},
                                related_name='related_to_student')
    created = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    course = models.ManyToManyField(Course, blank=True)
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default='New')
    price = models.DecimalField(max_digits=6, decimal_places=2, editable=False, blank=True, null=True)
    salary = models.DecimalField(max_digits=6, decimal_places=2, editable=False, blank=True, null=True)

    def __str__(self):
        return f"{self.student.username}'s ticket | Status - {self.status}"

skydash/ticket/forms.py
from django.forms import ModelForm
from django import forms

from ticket.models import Ticket


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ['mentor', 'student', 'location', 'course']
        widgets = {
            'course': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(TicketForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update(
                {
                    'class': 'form-control form-control-lg',
                    'placeholder': field.label,
                    'style': 'color: black'
                })

        self.fields['course'].widget.attrs.update(
            {
                'class': '',
            }
        )


class updateStatus(ModelForm):
    class Meta:
        model = Ticket
        fields = ['status']

    def __init__(self, *args, **kwargs):
        super(updateStatus, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update(
                {
                    'class': 'form-control form-control-lg',
                    'placeholder': field.label,
                    'style': 'color: black'
                })

skydash/custom_admin/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from custom_admin.utils import filterForAccount, filterForCourses
from ticket.models import Ticket
from courses.models import Course


# Create your views here.

@login_required(login_url='login')
def accounts(request):
    accounts, search_query = filterForAccount(request=request)

    context = {
        'accounts': accounts,
        'search_query': search_query
    }

    return render(request=request, template_name='custom_admin/accounts.html', context=context)


@login_required(login_url='login')
def courses(request):
    courses, search_query = filterForCourses(request=request)

    context = {
        'courses': courses,
        'search_query': search_query
    }

    return render(request=request, template_name='custom_admin/courses.html', context=context)


@login_required(login_url='login')
def tickets(request):
    tickets = Ticket.objects.all()

    context = {
        'tickets': tickets
    }

    return render(request=request, template_name='custom_admin/tickets.html', context=context)

skydash/ticket/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from ticket.forms import TicketForm, updateStatus
from ticket.models import Ticket


# Create your views here.

@login_required(login_url='login')
def createTicket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.save()
            form.save_m2m()
            form.save()
            return redirect('tickets')
    else:
        form = TicketForm()

    context = {
        'form': form,
    }

    return render(request=request, template_name='ticket/create.html', context=context)


@login_required(login_url='login')
def updateTicket(request, pk):
    ticket = Ticket.objects.get(id=pk)

    if request.method == 'POST':
        form = updateStatus(request.POST, instance=ticket)
        if form.is_valid():
            form.save()
            return redirect('tickets')
    else:
        form = updateStatus(instance=ticket)

    context = {
        'form': form,
        'pk': pk,
    }

    return render(request=request, template_name='ticket/update.html', context=context)


@login_required(login_url='login')
def deleteTicket(request, pk):
    ticket = Ticket.objects.get(id=pk)
    ticket.delete()

    return redirect('tickets')

skydash/custom_admin/templates/custom_admin/accounts.html
{% extends 'custom_admin/main.html' %}

{% load static %}

{% block content %}
    <div class="container-scroller">
        {% include 'custom_admin/navbar.html' %}
        <div class="container-fluid page-body-wrapper">
            {% include 'custom_admin/sidebar.html' %}
            <div class="main-panel">
                <div class="content-wrapper">

                    <div class="row">
                        <div class="col-md-12 grid-margin stretch-card">
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-title">{{ prof }}</p>
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="table-responsive">
                                                <table class="display-3 expandable-table table-hover"
                                                       style="width: 100%">

                                                    <thead>
                                                    <tr>
                                                        <th data-column="username" data-order="desc">Username</th>
                                                        <th data-column="age" data-order="desc">Age</th>
                                                        <th data-column="gender" data-order="desc">Gender</th>
                                                        <th>Phone</th>
                                                        <th>Email</th>
                                                        <th>Course</th>
                                                        <th data-column="payment" data-order="desc">Payment</th>
                                                    </tr>
                                                    </thead>

                                                    <tbody>
                                                    {% for account in accounts %}
                                                        <tr>
                                                            <td>
                                                                <a href="{% url 'update' account.id %}">
                                                                    {{ account.username }}
                                                                </a>
                                                            </td>
                                                            <td>{{ account.age }}</td>
                                                            <td>{{ account.gender }}</td>
                                                            <td>{{ account.phone_number }}</td>
                                                            <td>{{ account.email }}</td>
                                                            <td>
                                                                {% for course in account.course.all %}
                                                                    {{ course }}
                                                                    <br>
                                                                {% endfor %}
                                                            </td>
                                                            <td>{{ account.payment }}</td>
                                                        </tr>
                                                    {% endfor %}
                                                    </tbody>

                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021.  Premium <a
                            href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash. All rights reserved.</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i
                                class="ti-heart text-danger ml-1"></i></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
{% endblock content %}

skydash/custom_admin/templates/custom_admin/courses.html
{% extends 'custom_admin/main.html' %}

{% load static %}

{% block content %}
    <div class="container-scroller">
        {% include 'custom_admin/navbar.html' %}
        <div class="container-fluid page-body-wrapper">
            {% include 'custom_admin/sidebar.html' %}
            <div class="main-panel">
                <div class="content-wrapper">

                    <div class="row">

                        <div class="col-md-12 grid-margin stretch-card">
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-title">Courses</p>
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="table-responsive">
                                                <table class="display-3 expandable-table" style="width: 100%">

                                                    <thead>
                                                    <tr>
                                                        <th>Title</th>
                                                        <th>Duration</th>
                                                        <th>Price</th>
                                                    </tr>
                                                    </thead>

                                                    <tbody>
                                                    {% for course in courses %}
                                                        <tr>
                                                            <td>{{ course.title }}</td>
                                                            <td>{{ course.duration }} hours</td>
                                                            <td>{{ course.price }}$</td>
                                                        </tr>
                                                    {% endfor %}
                                                    </tbody>

                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021.  Premium <a
                            href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash. All rights reserved.</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i
                                class="ti-heart text-danger ml-1"></i></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
{% endblock content %}

skydash/custom_admin/templates/custom_admin/main.html
{% extends 'main.html' %}

{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/select.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/mdi/css/materialdesignicons.min.css' %}">
{% endblock styles %}

{% block scripts %}
    <script src="{% static 'vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'js/dataTables.select.min.js' %}"></script>
    <!-- Custom js for this page-->
    <script src="{% static 'js/dashboard.js' %}"></script>
    <script src="{% static 'js/Chart.roundedBarCharts.js' %}"></script>
    <!-- End custom js for this page-->

{% endblock scripts %}

skydash/custom_admin/templates/custom_admin/navbar.html
{% load static %}

<!-- partial:partials/_navbar.html -->
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo mr-5" href="{% url 'accounts' %}">
            <img src="{% static 'images/logo.svg' %}" class="mr-2" alt="logo"/></a>
        <a class="navbar-brand brand-logo-mini" href="{% url 'accounts' %}">
            <img src="{% static 'images/logo-mini.svg' %}" alt="logo"/></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="icon-menu"></span>
        </button>
        <ul class="navbar-nav mr-lg-2">
            <li class="nav-item nav-search d-none d-lg-block">
                <div class="input-group">
                    <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
                <span class="input-group-text" id="search">
                  <i class="icon-search"></i>
                </span>
                    </div>
                    <form action="" method="get">
                        <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now"
                               aria-label="search" aria-describedby="search" name="search_query"
                               value="{{ search_query }}">
                    </form>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                    Function
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="{% url 'ticket:create' %}">
                        <i class="ti-settings text-primary"></i>
                        Add order
                    </a>
                    <a class="dropdown-item" href="{% url 'logout' %}">
                        <i class="ti-power-off text-primary"></i>
                        Logout
                    </a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                data-toggle="offcanvas">
            <span class="icon-menu"></span>
        </button>
    </div>
</nav>
<!-- partial -->

skydash/custom_admin/templates/custom_admin/sidebar.html
<!-- partial:partials/_settings-panel.html -->
<!-- partial -->
<!-- partial:partials/_sidebar.html -->
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">

        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts' %}">
                <i class="icon-head menu-icon"></i>
                <span class="menu-title">Accounts</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'courses' %}">
                <i class="icon-paper menu-icon"></i>
                <span class="menu-title">Courses</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'tickets' %}">
                <i class="icon-contract menu-icon"></i>
                <span class="menu-title">Tickets</span>
            </a>
        </li>

    </ul>
</nav>
<!-- partial -->

skydash/custom_admin/templates/custom_admin/tickets.html
{% extends 'custom_admin/main.html' %}

{% load static %}

{% block content %}
    <div class="container-scroller">
        {% include 'custom_admin/navbar.html' %}
        <div class="container-fluid page-body-wrapper">
            {% include 'custom_admin/sidebar.html' %}
            <div class="main-panel">
                <div class="content-wrapper">

                    <div class="row">

                        <div class="col-md-12 grid-margin stretch-card">
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-title">Tickets</p>
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="table-responsive">
                                                <table class="display-3 expandable-table" style="width: 100%">

                                                    <thead>
                                                    <tr>
                                                        <th>id</th>
                                                        <th>Mentor</th>
                                                        <th>Student</th>
                                                        <th>Location</th>
                                                        <th>Courses</th>
                                                        <th>Price</th>
                                                        <th>Salary</th>
                                                        <th>Datetime</th>
                                                        <th>Status</th>
                                                    </tr>
                                                    </thead>

                                                    <tbody>
                                                    {% for ticket in tickets %}
                                                        <tr>
                                                            <td>
                                                                <a href="{% url 'ticket:update' ticket.id %}">{{ ticket.id }}</a>
                                                            </td>
                                                            <td>{{ ticket.mentor.username }}</td>
                                                            <td>{{ ticket.student.username }}</td>
                                                            <td>{{ ticket.location }}</td>
                                                            <td>
                                                                {% for course in ticket.course.all %}
                                                                    {{ course }}
                                                                    <br>
                                                                {% endfor %}
                                                            </td>
                                                            <td>{{ ticket.price }}$</td>
                                                            <td>{{ ticket.salary }}$</td>
                                                            <td>{{ ticket.created }}</td>
                                                            <td>{{ ticket.status }}</td>
                                                        </tr>
                                                    {% endfor %}
                                                    </tbody>

                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021.  Premium <a
                            href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash. All rights reserved.</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i
                                class="ti-heart text-danger ml-1"></i></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
{% endblock content %}